# Generated by Django 4.2.9 on 2024-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'name'), 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Kolejność'),
        ),
    ]
