# Generated by Django 5.0.1 on 2024-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='Czy w menu głównym'),
        ),
    ]
